Algoritmo "Soma2Numeros"
// 
//  
// Descrição   : Exercícios
// Autor(a)    : Victória Oliviera Ventrilho
// Data atual  : 09/03/2022
Var
// Seção de Declarações das variáveis 
Soma, x, y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Informe o valor de x")
 Leia(x)
 Escreva("Informe o valor de y")
 Leia(y)
 soma := x + y
 Escreva("Soma=", soma)
 
Fimalgoritmo