Algoritmo "OlaPessoa"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2022
Var
// Seção de Declarações das variáveis 
  nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreva("Qual o seu nome? ")
  leia(nome)
  Escreva("Olá, ",nome, "! Bom dia!")

Fimalgoritmo