Algoritmo "pitagoras"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2022
Var
// Seção de Declarações das variáveis 
  c1, c2, h : real


Inicio
escreva("Digite o primeiro cateto: ")
leia(c1)
escreval("Cateto 1 = ", c1)
escreva("Digite o segundo cateto: ")
leia(c2)
escreval("Cateto 2 = ", c2)
 h := raizq((c1^2) + (c2^2))
escreva("A hipotenusa desse triângulo vale ", h)


Fimalgoritmo