Algoritmo "ParOuImpar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2022
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(num)
se (num mod 2)=0 entao
   escreva("O número é par")
senao
     escreva("O número é impar")
fimse
     

Fimalgoritmo