Algoritmo "Calculadora v.2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis 
n, t: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o número para multiplicar: ")
leia(n)

para t de 1 ate 10 passo 1 faca
     escreval(n, " *",t, " =", n*t)
     fimpara

Fimalgoritmo