Algoritmo "Soma2Numeros"
// 
//  
// Descrição   : Atividades
// Autor(a)    : Luis Gustavo Marques Martins
// Data atual  : 09/03/2022
Var
// Seção de Declarações das variáveis 
soma, nx, ny: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe o valor de x: ")
   leia(nx)
   escreva("Informe o valor de y: ")
   leia(ny)
   soma := nx + ny
   escreva("Total é: ", soma)

Fimalgoritmo